### ISSUE TITLE
pip install errors

### ISSUE THREAD

**Issue by witten** [guokr/Anutshell#2]
This is in a virtualenv, which is why I'm using `--no-user`:

```
$ pip install brief --no-user
Collecting brief
  Downloading https://files.pythonhosted.org/packages/be/4f/aa79574c534b76183178ae167bd0772836dadfe1835a546292c8cf37a750/brief-0.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/witten/Downloads/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9z4ipgr2/brief/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9z4ipgr2/brief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9z4ipgr2/brief/pip-egg-info
         cwd: /tmp/pip-install-9z4ipgr2/brief/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9z4ipgr2/brief/setup.py", line 10, in <module>
        with open("requirements.txt", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'll just leave this here: https://caremad.io/posts/2013/07/setup-vs-requirement/

Environment: Python 3.7.4, virtualenv 16.1.0, Manjaro Linux stable

**Comment by NareshBisht** [comment]
Same with me
